Test Env loading issue
Test ENV does not eagerly load files by default. This causes issues with some solidus factories. The factory `shipped_order` for example raises a NameError:

> NameError: uninitialized constant SolidusFriendlyPromotions::FriendlyPromotionAdjuster::LoadPromotions

There are three ways I see and have confirmed that resolve the issue that have been presented here (as commments).
- In friendly_promotion_adjuster.rb explicitly require the files
- In friendly_promotion_adjuster.rb use dir to require all listed files. This approach is future proof, but lack intentionality
- In test_support require files preventing any unnecessary loading in production